## 練習時間
在小量的資料上，我們用眼睛就可以看得出來程式碼是否有跑出我們理想中的結果

請嘗試想像一個你需要的資料結構 (裡面的值可以是隨機的)，然後用上述的方法把它變成 pandas DataFrame

#### Ex: 想像一個 dataframe 有兩個欄位，一個是國家，一個是人口，求人口數最多的國家

### Hints: [隨機產生數值](https://blog.csdn.net/christianashannon/article/details/78867204)

In [7]:
import pandas as pd
import numpy as np

In [28]:
data = {'國家':['TW','US','UK','jp'] ,
        '人口': np.random.randint(0,10000,4)}
data = pd.DataFrame(data)
data

國家    人口
0  TW  8734
1  US  6731
2  UK  5877
3  jp  4272

In [29]:
data['國家'].iloc[data['人口'].idxmax(0)]

'TW'

In [15]:
 np.random.rand(10)

array([0.0451728 , 0.58497763, 0.46076279, 0.34208918, 0.67709416,
       0.35477992, 0.57149159, 0.46404476, 0.72775457, 0.23433275])

In [22]:
test_1=np.random.randn(10)

In [31]:
test_1


array([ 1.270687  ,  0.9127356 ,  0.50815095,  1.29713492, -2.91037591,
       -0.00968398,  0.06073068,  0.28860306, -0.10013285,  0.86644335])

In [8]:
 np.random.randint(10,size=10)

array([8, 7, 6, 8, 4, 3, 0, 1, 1, 2])

In [54]:
 np.random.randint(low=5,high=10,size=5)

array([6, 7, 5, 5, 7])

In [56]:
np.random.random_integers(5)

C:\Users\wu3so\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  """Entry point for launching an IPython kernel.


2

In [58]:
 np.random.randint(5,10,5)

array([5, 8, 8, 5, 7])

In [79]:
arr=np.arange(10)
print(arr)
np.random.shuffle(arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[2 7 3 8 9 1 5 6 0 4]


In [67]:
np.random.permutation(10)

array([7, 3, 0, 6, 8, 9, 2, 1, 4, 5])